import React from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const FractionalOwnership = () => {
  return (
    <div>
      <Header children={undefined} />

      <main>
        <h1>Fractional Ownership on BNBPropertyLink</h1>

        <section>
          <h2>Invest in Properties, Fractionally</h2>
          <p>
            BNBPropertyLink allows users to invest in high-value properties with fractional ownership.  Instead of purchasing an entire property outright, you can invest in a portion, gaining exposure to the potential appreciation and rental income. This opens up real estate investment to a broader range of investors, lowering the traditional financial barrier to entry.
          </p>
        </section>

        <section>
          <h2>Benefits of Fractional Ownership</h2>
          <ul>
            <li><b>Lower Investment Threshold:</b>  Invest in properties for a fraction of the total price.</li>
            <li><b>Diversification:</b> Spread your investment across multiple properties and reduce risk.</li>
            <li><b>Passive Income:</b> Generate passive income through rental income generated by the properties.</li>
            <li><b>Potential for Appreciation:</b>  Benefit from the potential increase in property value over time.</li>
            <li><b>Liquidity (Potential):</b> Depending on the property, there may be mechanisms to sell your fractional share.</li>
          </ul>
        </section>


        <section>
          <h2>How to Participate</h2>
          <ol>
            <li><b>Create an Account:</b> Sign up for a BNBPropertyLink account.</li>
            <li><b>Browse Properties:</b> Explore the available fractional ownership opportunities.</li>
            <li><b>Review Details:</b> Carefully examine the property details, including financial projections and legal documentation.</li>
            <li><b>Invest:</b>  Choose the property and the fraction you wish to own and complete the investment process.</li>
            <li><b>Manage your Investment:</b> Monitor your investment and track your returns on the platform.</li>
          </ol>
        </section>
      </main>

      <Footer children={undefined} />
    </div>
  );
};

export default FractionalOwnership;